### ISSUE TITLE
OverlappingFileLockException

### ISSUE THREAD

**Issue by suvratdwivedi** [renatoathaydes/spock-reports#131]
I have two separate set of test folders one is for integration test and one is for unit test. Once the spock-report tries to collate the report it throws the following exception::-

`16:00:52.658 [org.spockframework.runtime.RunContext.stop(), ,] WARN  c.a.s.r.i.HtmlReportAggregator - Failed to create aggregated report
java.nio.channels.OverlappingFileLockException: null
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1063)
        at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
        at java_nio_channels_FileChannel$lock.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at com.athaydes.spockframework.report.internal.ReportDataAggregator.getAllAggregatedDataAndPersistLocalData(ReportDataAggregator.groovy:26)
        at com.athaydes.spockframework.report.internal.ReportDataAggregator$getAllAggregatedDataAndPersistLocalData.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214)
        at com.athaydes.spockframework.report.internal.HtmlReportAggregator.writeOut(HtmlReportAggregator.groovy:44)
        at com.athaydes.spockframework.report.internal.HtmlReportAggregator$writeOut$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:80)
        at com.athaydes.spockframework.report.internal.HtmlReportCreator.done(HtmlReportCreator.groovy:101)
        at com.athaydes.spockframework.report.IReportCreator$done$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:80)
        at com.athaydes.spockframework.report.SpockReportExtension.stop(SpockReportExtension.groovy:66)
        at org.spockframework.runtime.GlobalExtensionRegistry.stopGlobalExtensions(GlobalExtensionRegistry.java:111)
        at org.spockframework.runtime.RunContext.stop(RunContext.java:67)
        at org.spockframework.runtime.RunContext.access$000(RunContext.java:30)
        at org.spockframework.runtime.RunContext$2.run(RunContext.java:159)
`

**Comment by renatoathaydes** [comment]
Wow... the report aggregator should catch this Exception and retry after a little wait!

Will fix it soon. Thanks for reporting.

**Comment by VigneshPalanisamy** [comment]
Hi, is there any update or work around for this issue.

**Comment by renatoathaydes** [comment]
Not yet. Have you had this problem happen often?

**Comment by VigneshPalanisamy** [comment]
No, If i extend some of my test class with ElectricSpecification and other with Specification i get this error.

**Comment by suvratdwivedi** [comment]
Is there any plan on fixing it?

**Comment by renatoathaydes** [comment]
It's an easy fix, contributions welcome. I have been busy with other projects, unfortunately. Let me know if you need any help.

**Comment by renatoathaydes** [comment]
Can someone experiencing this problem please provide a simple Spec that reproduces this problem?

**Comment by renatoathaydes** [comment]
I've written a  test that verifies my fix works using 2 JVMs, writing reports from 20 Threads each. So this should definitely fix the issue.
