### ISSUE TITLE
"Cannot compare java.util.ArrayList with value '[]' and java.lang.Integer with value '0'" Exception with TemplateReportCreator - 2.0.1-RC3

### ISSUE THREAD

**Issue by ziffit** [renatoathaydes/spock-reports#210]
Hi,
i am trying to integrate spock-reports in the latest Version into a simple project. 

HtmlReportCreator is running fine. 

When i am switching in my properties to TemplateReportCreator i get the stacktrace below.

`
[main] WARN com.athaydes.spockframework.report.template.TemplateReportCreator - Unexpected error creating report
java.lang.IllegalArgumentException: Cannot compare java.util.ArrayList with value '[]' and java.lang.Integer with value '0'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareToWithEqualityCheck(DefaultTypeTransformation.java:612)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareTo(DefaultTypeTransformation.java:541)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareTo(ScriptBytecodeAdapter.java:716)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareGreaterThan(ScriptBytecodeAdapter.java:766)
	at groovy.tmp.templates.GStringTemplateScript1$_getTemplate_closure1$_closure3.doCall(GStringTemplateScript1.groovy:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	....
`
I'm not shure if i am missing a configuration, or if this is a bug.

[stacktrace.txt](https://github.com/renatoathaydes/spock-reports/files/6353268/stacktrace.txt)

[com.athaydes.spockframework.report.IReportCreator.properties.txt](https://github.com/renatoathaydes/spock-reports/files/6353255/com.athaydes.spockframework.report.IReportCreator.properties.txt)

[pom.xml.txt](https://github.com/renatoathaydes/spock-reports/files/6353249/pom.xml.txt)

**Comment by renatoathaydes** [comment]
You seem to be using Java 11+ and JUnit 5. Are you also using spock `2.0-M4-groovy-3.0` and spock-reports version `2.0.1-RC3`?

**Comment by ziffit** [comment]
Tested the same project on a different machine. Now it is working. :-(
Perhabs there was a difference in the jdk I used.
I'll close the bug.
